app = "upsa-pax-romana"
primary_region = "iad"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[env]
APP_NAME = "ST. GREGORY THE GREAT CATHOLIC CHAPLAINACY - UPSA"
APP_ENV = "production"
# APP_KEY is set via Fly secret
APP_DEBUG = false
APP_URL = "https://upsa-pax-romana.fly.dev"
FRONTEND_URL = "https://upsa-pax-romana.fly.dev"
CORS_ALLOWED_ORIGINS = "https://upsa-pax-romana.fly.dev"
SANCTUM_STATEFUL_DOMAINS = "upsa-pax-romana.fly.dev"

APP_LOCALE = "en"
APP_FALLBACK_LOCALE = "en"
APP_FAKER_LOCALE = "en_US"

APP_MAINTENANCE_DRIVER = "file"
# APP_MAINTENANCE_STORE=database

PHP_CLI_SERVER_WORKERS = 4

BCRYPT_ROUNDS = 12

LOG_CHANNEL = "stderr"
LOG_STACK = "single"
# LOG_DEPRECATIONS_CHANNEL=null
LOG_LEVEL = "info"

DB_CONNECTION = "mysql"

SESSION_DRIVER = "file"
SESSION_LIFETIME = 30
SESSION_ENCRYPT = false
SESSION_PATH = "/"
SESSION_DOMAIN = "upsa-pax-romana.fly.dev"
SESSION_SECURE_COOKIE = true
SESSION_SAME_SITE = "lax"
SESSION_EXPIRE_ON_CLOSE = true

BROADCAST_CONNECTION = "log"
FILESYSTEM_DISK = "local"
QUEUE_CONNECTION = "sync"

CACHE_STORE = "file"
CACHE_DRIVER = "file"
# CACHE_PREFIX=

MEMCACHED_HOST = "127.0.0.1"

REDIS_CLIENT = "phpredis"
REDIS_HOST = "127.0.0.1"
REDIS_PASSWORD = "null"
REDIS_PORT = 6379

MAIL_MAILER = "resend"
MAIL_SCHEME = "null"
MAIL_HOST = "smtp.resend.com"
MAIL_PORT = 587
MAIL_USERNAME = "resend"
MAIL_PASSWORD = "null"
MAIL_ENCRYPTION = "tls"
MAIL_FROM_ADDRESS = ""
MAIL_FROM_NAME = "ST. GREGORY THE GREAT CATHOLIC CHAPLAINACY - UPSA"

RESEND_API_KEY = ""

AWS_ACCESS_KEY_ID = ""
AWS_SECRET_ACCESS_KEY = ""
AWS_DEFAULT_REGION = "us-east-1"
AWS_BUCKET = ""
AWS_USE_PATH_STYLE_ENDPOINT = false

VITE_APP_NAME = "ST. GREGORY THE GREAT CATHOLIC CHAPLAINACY - UPSA"

PAYSTACK_PUBLIC_KEY = ""
PAYSTACK_SECRET_KEY = ""
PAYSTACK_PAYMENT_URL = ""
MERCHANT_EMAIL = ""

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1