app = "upsa-pax-romana"
primary_region = "iad"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[env]
  APP_ENV = "production"
  APP_DEBUG = "false"
  LOG_CHANNEL = "stderr"
  SESSION_DRIVER = "database"
  CACHE_DRIVER = "database"

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1